#!/bin/env python3
import json

template = """// Deviceinfo.h
// AUTOGENERATED FILE
// DO NOT CHANGE 

#ifndef DEVICEINFO_H
#define DEVICEINFO_H

const uint8_t DEVICEINFO_PAYLOAD[] PROGMEM = "{device_info}";
const int DEVICEINFO_PAYLOAD_SIZE = {device_info_len};

#endif // DEVICEINFO_H

"""

with open("DeviceInfo.json", "r") as fi:
    device_info = json.dumps(json.load(fi))
    device_info_len = len(device_info)
    device_info_replaced = device_info.replace(r'"', r'\"')

    with open("DeviceInfo.h", "w") as fo:
        fo.write(
            template.format(
                device_info=device_info_replaced,
                device_info_len=device_info_len
            )
        )
