// Deviceinfo.h
// AUTOGENERATED FILE
// DO NOT CHANGE 

#ifndef DEVICEINFO_H
#define DEVICEINFO_H

const uint8_t DEVICEINFO_PAYLOAD[] PROGMEM = "{\"deviceInfo\": {\"name\": \"relay01\", \"endPoints\": {\"set\": {\"values\": {\"value\": true}, \"card-type\": \"crouton-simple-toggle\", \"title\": \"Relay01 set\"}, \"toggle\": {\"values\": {\"value\": true}, \"icons\": {\"icon\": \"bolt\"}, \"card-type\": \"crouton-simple-button\", \"title\": \"Relay01 Toggle\"}}, \"description\": \"Lets make relay great again.\", \"status\": \"good\", \"color\": \"#f4b642\", \"version\": 1}}";
const int DEVICEINFO_PAYLOAD_SIZE = 378;

#endif // DEVICEINFO_H

